namespace WebLogger.Generators
{
    internal static class Constants
    {
        public const string Namespace = "WebLogger";

        public const string CommandInterface = "WebLogger.IWebLoggerCommand";

        public const string CommandHandlerAttributeFile = @"CommandHandlerAttribute.g.cs";
        public const string CommandHandlerAttributeName = "WebLogger.Generators.CommandHandlerAttribute";
        public const string CommandHandlerAttributeValue =
@"
// <auto-generated/>

namespace WebLogger.Generators
{
    /// <summary>
    /// When applied to a method on a partial class the class will be converted to an IWebLoggerCommand
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""WebLogger"", ""1.1.3"")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
    public class CommandHandlerAttribute : global::System.Attribute
    {
        /// <summary>
        /// Name of the command used as the command key
        /// </summary>
        public string Command { get; private set; }
        /// <summary>
        /// Description of the command displayed in the output of the help command.
        /// </summary>
        public string Description { get; private set; }
        /// <summary>
        /// Message that describes the usage for the command.
        /// </summary>
        public string Help { get; private set; }

        /// <summary>
        /// Default constructor sets all required properties.
        /// </summary>
        /// <param name=""command""></param>
        /// <param name=""description""></param>
        /// <param name=""help""></param>
        public CommandHandlerAttribute(
            string command,
            string description,
            string help)
        {
            Command = command;
            Description = description;
            Help = help;
        }
    }
}";
        public const string WebLoggerCommandAttributeFile = @"WebLoggerCommandAttribute.g.cs";
        public const string WebLoggerCommandAttributeName = @"WebLoggerCommandAttribute";
        public const string WebLoggerCommandAttributeValue =
@"
// <auto-generated/>

namespace WebLogger.Generators
{
    /// <summary>
    /// When applied to a partial class the class will be converted to an IWebLoggerCommand.
    /// The command handler will need to be marked with the CommandHandlerAttriibute
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""WebLogger"", ""1.1.3"")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
    public class WebLoggerCommandAttribute : global::System.Attribute
    {
    }
}";
    }
}